name: Python Program Check

on:
  push:
    branches:
      - main

jobs:
  check-python-program:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.0

    - name: Run Python script
      run: index.py
